### ISSUE TITLE
Doesn't work with nightly builds of typescript (1.6)

### ISSUE THREAD

**Issue by prabirshrestha** [jbrantly/ts-loader#24]
Need to try out jsx react support so when I use the nightly builds of typescript `npm install ntypescript` I get error.

```
D:\temp\reactjs-typescript-boilerplate>npm run build

> reactjs-typescript-boilerplate@1.0.0 build D:\temp\reactjs-typescript-boilerpl
ate
> webpack --config=webpack.config.js --progress --colors --devtool source-map

 50% 2/3 build modulesUsing config file at D:\temp\reactjs-typescript-boilerplat
e\src\tsconfig.json
Hash: 4752b7dc0a2e5b3df26e
Version: webpack 1.10.1
Time: 328ms
   [0] multi app 28 bytes {0} [built] [1 error]
   [0] multi app.specs 16 bytes {1} [built]
    + 1 hidden modules

ERROR in ./src/App.tsx
Module build failed: TypeError: host.readDirectory is not a function
    at getFileNames (D:\temp\reactjs-typescript-boilerplate\node_modules\ntypesc
ript\bin\typescript.js:34793:37)
    at Object.parseConfigFile (D:\temp\reactjs-typescript-boilerplate\node_modul
es\ntypescript\bin\typescript.js:34740:24)
    at ensureTypeScriptInstance (D:\temp\reactjs-typescript-boilerplate\node_mod
ules\ts-loader\index.js:83:42)
    at Object.loader (D:\temp\reactjs-typescript-boilerplate\node_modules\ts-loa
der\index.js:191:20)
 @ multi app
```

You can repo the issue from https://github.com/prabirshrestha/reactjs-typescript-boilerplate/tree/webpack (webpack) branch

```bash
npm install
npm run build
```

given that TS 1.6 is not officially out might be better to have an alpha version of `ts-loader`.

**Comment by jbrantly** [comment]
This has been added in v0.4.6 which has been published to npm. Instead of publishing an alpha build I just make it compatible with both TS 1.5.0-beta and the nightly, so you can use either. I also created [a JSX test](https://github.com/jbrantly/ts-loader/tree/master/test/jsx) that you might be interested in.
